apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ricardoamaro/drupal_cncf.git'
    path: argoapps/tekton
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
