drupalUsername: "admin"
drupalPassword: "StrongPassword"
drupalEmail: "admin@example.com"
mariadb:
  auth:
    rootPassword: "MariaDBRootPassword"
    database: "drupal"
    username: "drupal"
    password: "DrupalDBPassword"
ingress:
  enabled: true
  className: "" # Use this if you are using Kubernetes 1.18+
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - name: drupal.example.com
      path: /
      pathType: ImplementationSpecific
  tls:
    - secretName: drupal-tls
      hosts:
        - drupal.example.com
persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 5Gi